image: tetraweb/php:7.1

variables:
    COMPOSER_CACHE_DIR: /cache/composer
    COMPOSER_MEMORY_LIMIT: -1
    COMPOSER_ALLOW_SUPERUSER: 1

.unittest:
    coverage: '/^\s*Lines:\s*\d+.\d+\%/'
    script:
        - composer require oro/platform:${ORO_VERSION}  --ignore-platform-reqs --no-update
        - composer update --no-interaction --ignore-platform-reqs
        - docker-php-ext-enable xdebug
        - vendor/bin/phpunit --coverage-text --colors=never .

unittest:2.6:
    extends: .unittest
    variables:
        ORO_VERSION: 2.6.*

unittests:3.0:
    extends: .unittest
    variables:
        ORO_VERSION: 3.0.*

unittests:3.2:
    extends: .unittest
    variables:
        ORO_VERSION: 3.2.*

unittests:latest:
    extends: .unittest
    allow_failure: true
    variables:
        ORO_VERSION: dev-master