datagrids:
    dmk-duplicates-grid:
        acl_resource: dmk_duplicate_view
        source:
            type: orm
            query:
                select:
                    - duplicate.class
                    - duplicate.id
                    - duplicate.name
                    - duplicate.objectId
                    - duplicate.weight
                    - duplicate.createdAt
                from:
                    - { table: DMKDuplicateCheckBundle:Duplicate, alias: duplicate }
                where:
                    and:
                        - duplicate.objectId = :objectId
                        - duplicate.class = :objectClass
            bind_parameters:
                - object_id
                - object_class
        columns:
            id:
                renderable: false
                manageable: false
            objectId:
                label: dmk.duplicatecheck.duplicate.object_id.label
                frontend_type: integer
                renderable: false
            class:
                label: dmk.duplicatecheck.duplicate.class.label
                type: callback
                callable: "@dmk_duplicate_check.datagrid.entity_type_provider->getEntityType"
            name:
                label: dmk.duplicatecheck.duplicate.name.label
            weight:
                label: dmk.duplicatecheck.duplicate.weight.label
                frontend_type: integer
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
        sorters:
            columns:
                objectId:
                    data_name: duplicate.objectId
                class:
                    data_name: duplicate.class
                createdAt:
                    data_name: duplicate.createdAt
                weight:
                    data_name: duplicate.weight
            default:
                weight: DESC
        filters:
            columns:
                objectId:
                    type: number-range
                    data_name: duplicate.objectId
                weight:
                    type: number-range
                    data_name: duplicate.weight
                class:
                    type: choice
                    data_name: duplicate.class
                    options:
                        field_options:
                            choices: "@dmk_duplicate_check.datagrid.entity_type_provider->getEntityTypes"
